name: .NET Core

on:  
    push:
        branches-ignore:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run: dotnet test ./SFX.Random.sln --configuration Release 
    - name: Build NuGet Packages
      run: dotnet pack ./SFX.Random.sln --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o ./nuget
    - name: Deploy NuGet Packages
      run: dotnet nuget push /home/runner/work/SFX.Random/SFX.Random/nuget/SFX.Random*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
